import svg from '../../images/present.svg';
import logo from '../../images/logoKura.png';
import ah from '../../images/chc.svg';
import prog from '../../images/prog.svg';
import design from '../../images/design.svg';
import logClass from '../../images/iconCornu.png';
import cdcClass from '../../images/Cdcclass.svg';
import desClass from '../../images/designClass.svg';
import progClass from '../../images/progClass.svg';
import QrCode from '../../images/frame.png';

export const homeObjOne = {
	id: 'about',
	lightbg: false,
	lightText: true,
	lightTextDesc: true,
	topLine: 'About',
	headline: 'Présentation :',
	description: "J'ai 20 ans, je suis étudiant en Licence général Informatique. Je suis passionné de Jeux Vidéo et de programmation dont je cherche à faire mon métier. Mon projet professionnel est de devenir développeur Jeux Video / Blockchain. C'est pourquoi j'ai commencé par faire un Bac Pro SN option \"Réseaux Informatiques et Systèmes Communicants\" pour ensuite me diriger sur un BTS System Numérique. Ainsi je souhaiterais continuer mon cursus scolaire avec un Master dans le domaine du développement.",
	buttonLabel: 'Continue',
	imgStart: false,
	img: svg,
	alt: 'About',
	dark: true,
	primary: true,
	darkText: false,
	primarybtn: 'true',
	direction: 'project',
	buttondirection: true,
};
export const homeObjTwo = {
	id: 'project',
	lightbg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'Project',
	headline: 'Kura 2048 (Beta)',
	description: 'c\'est un jeu video de type "HyperCasual" que j\'ai développé durant mon temps libre en C# sur Unity.',
	buttonLabel: 'Click for details',
	imgStart: true,
	img: logo,
	alt: 'Car',
	dark: false,
	primary: true,
	darkText: true,
	direction: '/kuraproject',
	buttondirection: false,
};

export const homeObjThree = {
	id: 'project',
	lightbg: false,
	lightText: true,
	lightTextDesc: true,
	topLine: 'Project',
	headline: 'Ma Classe Entremêlée',
	description: "Ceci est un projet que j'ai réalisé pendant mon cursus scolaire pour l'épreuve du BTS",
	buttonLabel: 'Click for details',
	imgStart: false,
	img: logClass,
	alt: 'CornuIcon',
	dark: true,
	primary: true,
	darkText: false,
	primarybtn: 'true',
	direction: '/btsproject',
	buttondirection: false,
};
export const homeObjFour = {
	id: 'desc',
	lightbg: false,
	lightText: true,
	lightTextDesc: true,
	topLine: 'Description',
	headline: 'Kura 2048',
	description: 'Kura 2048 est un HyperCasual Game se jouant sur mobile sous Android ce project à été entièrement fais sur Unity en C# réalisé sur mon temps libre ',
	buttonLabel: 'Continue',
	imgStart: false,
	img: logo,
	alt: 'Kura2048',
	dark: true,
	primary: true,
	darkText: false,
	primarybtn: 'true',
	direction: 'cdc',
	buttondirection: true,
};

export const homeObjFive = {
	id: 'cdc',
	lightbg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: '',
	headline: 'Cahier des charges',
	description: "Pour ce projet j'ai voulu réalisé un jeu sur la plateforme Android. le but étais de refaire un 2048 sous une autre forme que son original, il fallait imposer une difficulté au joueur afin qu'il puisse terminer sa partie et en recommencer une afin de rendre le jeu addictif sans être trop compliqué ainsi que lassant.",
	buttonLabel: 'Continue',
	imgStart: true,
	img: ah,
	alt: 'Kura2048',
	dark: false,
	primary: true,
	darkText: true,
	direction: 'dev',
	buttondirection: true,
};

export const homeObjSix = {
	id: 'dev',
	lightbg: false,
	lightText: true,
	lightTextDesc: true,
	topLine: 'Developpement',
	headline: 'Programmation',
	description: "Développer sur Unity avec le language C#, avec ce projet j'ai utilisé des API comme celle de GooglePlay afin de récupérer les noms d'utilisateurs et la sauvegarde dans le cloud, ou même celle de LootLocker qui me permet une gestion des tableaux de score ainsi que quelques données pouvant être enregistré avec.",
	buttonLabel: 'Continue',
	imgStart: false,
	img: prog,
	alt: 'Kura2048',
	dark: true,
	primary: true,
	darkText: false,
	primarybtn: 'true',
	direction: 'design',
	buttondirection: true,
};

export const homeObjSeven = {
	id: 'design',
	lightbg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'Developpement',
	headline: 'Design',
	description: "Le design remodelé plusieurs fois au cours de sa version de test, toute fois il reste encore assez basique malgrès son univers, d'autres mises à jour viendrons par la suite afin de renforcer la personnalisation utilisateur.",
	buttonLabel: 'Continue',
	imgStart: true,
	img: design,
	alt: 'Kura2048',
	dark: false,
	primary: true,
	darkText: true,
	direction: 'qrc',
	buttondirection: true,
};

export const homeObjDescC = {
	id: 'desc',
	lightbg: false,
	lightText: true,
	lightTextDesc: true,
	topLine: 'Description',
	headline: 'Ma Classe Entremêlée',
	description: 'Ce projet à été découpé et se comporte de plusieurs partie, une partie avec un entierement dirigé sur un client Web et ma partie axée sur une application android.',
	buttonLabel: 'Continue',
	imgStart: false,
	img: logClass,
	alt: 'Kura2048',
	dark: true,
	primary: true,
	darkText: false,
	primarybtn: 'true',
	direction: 'cdc',
	buttondirection: true,
};

export const homeObjCdc = {
	id: 'cdc',
	lightbg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: '',
	headline: 'Cahier des charges',
	description: "L'application android à pour but d'améliorer l'autonomie de l'élève, grâce à cette application qui permet de renseigner en temps réel les informations utiles qui pourront par la suite être traitées et analysée par l'interface Web",
	buttonLabel: 'Continue',
	imgStart: true,
	img: cdcClass,
	alt: 'Kura2048',
	dark: false,
	primary: true,
	darkText: true,
	direction: 'dev',
	buttondirection: true,
};

export const homeObjProg = {
	id: 'dev',
	lightbg: false,
	lightText: true,
	lightTextDesc: true,
	topLine: 'Developpement',
	headline: 'Programmation',
	description: "l'Application développée principalement en Java sous Android studio avec une partie relation base de données en PHP afin de faire la gestion des différentes données proprement.",
	buttonLabel: 'Continue',
	imgStart: false,
	img: progClass,
	alt: 'Kura2048',
	dark: true,
	primary: true,
	darkText: false,
	primarybtn: 'true',
	direction: 'design',
	buttondirection: true,
};

export const homeObjDesign = {
	id: 'design',
	lightbg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'Developpement',
	headline: 'Design',
	description: "Le design doit impérativement être attrayant, afin que les élèves qui l'utiliseront au quotidien ne soit pas lassée lors de son utilisation pour leurs activités de projets.",
	buttonLabel: 'Continue',
	imgStart: true,
	img: desClass,
	alt: 'Kura2048',
	dark: false,
	primary: true,
	darkText: true,
	direction: 'img',
	buttondirection: true,
};

export const homeObjQrCode = {
	id: 'qrc',
	lightbg: false,
	lightText: true,
	lightTextDesc: true,
	topLine: 'Google Play',
	headline: 'QrCode',
	description: 'Voici un petit QrCode que vous pouvez scanner pour rejoindre le projet directement sur Google Play.',
	buttonLabel: 'Continue',
	imgStart: false,
	img: QrCode,
	alt: 'QrCode',
	dark: true,
	primary: true,
	darkText: false,
	primarybtn: 'true',
	direction: 'img',
	buttondirection: true,
};
